import React,{useState} from "react";
import Navbar from "./Navbar";
import SearchBar from "./SearchBar";
import PropertyGrid from "./PropertyGrid";
import Footer from "./Footer";
import "./SearchResultsGrid"

/* Example listings */
const popularThisWeek = [
    {
        id: 1,
        image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
        title: "Modern Apartment in Borrowdale",
        location: "Harare",
        price: 450,
        rooms: 2,
        type: "Apartment",
        borehole: true,
        gated: true,
        solar: false,
    },
    {
        id: 2,
        image: "https://images.unsplash.com/photo-1572120360610-d971b9d7767c",
        title: "Family House in Greendale",
        location: "Harare",
        price: 600,
        rooms: 3,
        type: "House",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 3,
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
        title: "Luxury Villa in Mount Pleasant",
        location: "Harare",
        price: 1200,
        rooms: 4,
        type: "Villa",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 4,
        image: "https://images.unsplash.com/photo-1599423300746-b62533397364",
        title: "Neat Flat in Avondale",
        location: "Harare",
        price: 500,
        rooms: 2,
        type: "Apartment",
        borehole: true,
        gated: false,
        solar: false,
    },
    {
        id: 5,
        image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
        title: "Townhouse in Newlands",
        location: "Harare",
        price: 750,
        rooms: 3,
        type: "Townhouse",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 6,
        image: "https://images.unsplash.com/photo-1600047509358-9dc75507daeb",
        title: "Cottage in Waterfalls",
        location: "Harare",
        price: 380,
        rooms: 2,
        type: "Cottage",
        borehole: true,
        gated: true,
        solar: false,
    },
    {
        id: 7,
        image: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6",
        title: "Garden Flat in Milton Park",
        location: "Harare",
        price: 420,
        rooms: 1,
        type: "Flat",
        borehole: false,
        gated: true,
        solar: false,
    },
    {
        id: 8,
        image: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83",
        title: "Executive Home in Highlands",
        location: "Harare",
        price: 950,
        rooms: 4,
        type: "House",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 9,
        image: "https://images.unsplash.com/photo-1600585152915-d208bec867a1",
        title: "Modern Duplex in Eastlea",
        location: "Harare",
        price: 680,
        rooms: 3,
        type: "Duplex",
        borehole: true,
        gated: true,
        solar: false,
    },
    {
        id: 10,
        image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
        title: "Secure Apartment in CBD",
        location: "Harare",
        price: 400,
        rooms: 1,
        type: "Apartment",
        borehole: false,
        gated: true,
        solar: false,
    },
];

const newListings = [
    {
        id: 11,
        image: "https://images.unsplash.com/photo-1599423300746-b62533397364",
        title: "Compact Studio in Avenues",
        location: "Harare",
        price: 350,
        rooms: 1,
        type: "Studio",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 12,
        image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
        title: "Townhouse in Avondale",
        location: "Harare",
        price: 700,
        rooms: 3,
        type: "Townhouse",
        borehole: true,
        gated: true,
        solar: false,
    },
    {
        id: 13,
        image: "https://images.unsplash.com/photo-1600047509358-9dc75507daeb",
        title: "Neat Cottage in Waterfalls",
        location: "Harare",
        price: 400,
        rooms: 2,
        type: "Cottage",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 14,
        image: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6",
        title: "Bachelor Flat in Hatfield",
        location: "Harare",
        price: 300,
        rooms: 1,
        type: "Flat",
        borehole: false,
        gated: true,
        solar: false,
    },
    {
        id: 15,
        image: "https://images.unsplash.com/photo-1600585154207-2fbdcbb96b36",
        title: "Modern House in Marlborough",
        location: "Harare",
        price: 820,
        rooms: 4,
        type: "House",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 16,
        image: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83",
        title: "Secure Cluster Home in Bluff Hill",
        location: "Harare",
        price: 650,
        rooms: 3,
        type: "Cluster",
        borehole: true,
        gated: true,
        solar: false,
    },
    {
        id: 17,
        image: "https://images.unsplash.com/photo-1600585152915-d208bec867a1",
        title: "Stylish Apartment in CBD",
        location: "Harare",
        price: 480,
        rooms: 2,
        type: "Apartment",
        borehole: false,
        gated: true,
        solar: false,
    },
    {
        id: 18,
        image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
        title: "New Build in Prospect",
        location: "Harare",
        price: 550,
        rooms: 3,
        type: "House",
        borehole: true,
        gated: false,
        solar: false,
    },
    {
        id: 19,
        image: "https://images.unsplash.com/photo-1600585153490-76fb20a32601",
        title: "Spacious Home in Chisipite",
        location: "Harare",
        price: 1100,
        rooms: 5,
        type: "House",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 20,
        image: "https://images.unsplash.com/photo-1588854337118-1c4b82bbec56",
        title: "Affordable Flat in Mbare",
        location: "Harare",
        price: 250,
        rooms: 1,
        type: "Flat",
        borehole: false,
        gated: false,
        solar: false,
    },
];

const guesthouses = [
    {
        id: 101,
        image: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
        title: "Palm Court Guesthouse",
        location: "Avondale, Harare",
        price: 55,
        rooms: 1,
        type: "Guesthouse",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 102,
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
        title: "Highlands Executive Guesthouse",
        location: "Highlands, Harare",
        price: 70,
        rooms: 1,
        type: "Guesthouse",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 103,
        image: "https://images.unsplash.com/photo-1523217582562-09d0def993a6",
        title: "Cosy Guest Lodge",
        location: "Mount Pleasant, Harare",
        price: 60,
        rooms: 1,
        type: "Guesthouse",
        borehole: true,
        gated: true,
        solar: false,
    },
    {
        id: 104,
        image: "https://images.unsplash.com/photo-1590490360182-c33d57733427",
        title: "Avenues Guest Suites",
        location: "Avenues, Harare",
        price: 50,
        rooms: 1,
        type: "Guesthouse",
        borehole: false,
        gated: true,
        solar: false,
    },
    {
        id: 105,
        image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
        title: "Greendale Guesthouse",
        location: "Greendale, Harare",
        price: 45,
        rooms: 1,
        type: "Guesthouse",
        borehole: true,
        gated: true,
        solar: false,
    },
    {
        id: 106,
        image: "https://images.unsplash.com/photo-1600585152220-90363fe7e115",
        title: "Borrowdale Boutique Stay",
        location: "Borrowdale, Harare",
        price: 80,
        rooms: 1,
        type: "Guesthouse",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 107,
        image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
        title: "Westgate Guest Lodge",
        location: "Westgate, Harare",
        price: 48,
        rooms: 1,
        type: "Guesthouse",
        borehole: true,
        gated: false,
        solar: false,
    },
    {
        id: 108,
        image: "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba",
        title: "Emerald Guesthouse",
        location: "Milton Park, Harare",
        price: 52,
        rooms: 1,
        type: "Guesthouse",
        borehole: false,
        gated: true,
        solar: false,
    },
    {
        id: 109,
        image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
        title: "Tranquil Stay Guesthouse",
        location: "Newlands, Harare",
        price: 65,
        rooms: 1,
        type: "Guesthouse",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 110,
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
        title: "CBD Guesthouse",
        location: "Harare CBD",
        price: 40,
        rooms: 1,
        type: "Guesthouse",
        borehole: false,
        gated: true,
        solar: false,
    },
];

const boardingHouses = [
    {
        id: 201,
        image: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c",
        title: "Belvedere Boarding House",
        location: "Belvedere, Harare",
        price: 150,
        rooms: 1,
        type: "Boarding House",
        borehole: true,
        gated: true,
        solar: false,
    },
    {
        id: 202,
        image: "https://images.unsplash.com/photo-1588854337118-1d3f6f99d73a",
        title: "Student Boarding – Avondale",
        location: "Avondale, Harare",
        price: 180,
        rooms: 1,
        type: "Boarding House",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 203,
        image: "https://images.unsplash.com/photo-1600585152125-3d66a4f5c18b",
        title: "Affordable Rooms in Waterfalls",
        location: "Waterfalls, Harare",
        price: 120,
        rooms: 1,
        type: "Boarding House",
        borehole: true,
        gated: false,
        solar: false,
    },
    {
        id: 204,
        image: "https://images.unsplash.com/photo-1599423300746-b62533397364",
        title: "Dzivarasekwa Boarding House",
        location: "Dzivarasekwa, Harare",
        price: 100,
        rooms: 1,
        type: "Boarding House",
        borehole: false,
        gated: true,
        solar: false,
    },
    {
        id: 205,
        image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
        title: "Mbare Boarding Rooms",
        location: "Mbare, Harare",
        price: 90,
        rooms: 1,
        type: "Boarding House",
        borehole: true,
        gated: false,
        solar: false,
    },
    {
        id: 206,
        image: "https://images.unsplash.com/photo-1600047509358-9dc75507daeb",
        title: "Highfield Shared Housing",
        location: "Highfield, Harare",
        price: 130,
        rooms: 1,
        type: "Boarding House",
        borehole: true,
        gated: true,
        solar: false,
    },
    {
        id: 207,
        image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
        title: "Kuwadzana Boarding House",
        location: "Kuwadzana, Harare",
        price: 110,
        rooms: 1,
        type: "Boarding House",
        borehole: false,
        gated: false,
        solar: false,
    },
    {
        id: 208,
        image: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
        title: "Glen View Boarding Rooms",
        location: "Glen View, Harare",
        price: 95,
        rooms: 1,
        type: "Boarding House",
        borehole: true,
        gated: true,
        solar: false,
    },
    {
        id: 209,
        image: "https://images.unsplash.com/photo-1572120360610-d971b9d7767c",
        title: "Hatfield Boarding House",
        location: "Hatfield, Harare",
        price: 140,
        rooms: 1,
        type: "Boarding House",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 210,
        image: "https://images.unsplash.com/photo-1527030280862-64139fba04ca",
        title: "Chitungwiza Boarding Rooms",
        location: "Chitungwiza",
        price: 85,
        rooms: 1,
        type: "Boarding House",
        borehole: true,
        gated: false,
        solar: false,
    },
];

const shortStays = [
    {
        id: 301,
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
        title: "Luxury Holiday Villa",
        location: "Borrowdale, Harare",
        price: 120,
        rooms: 4,
        type: "Short Stay",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 302,
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
        title: "Modern Airbnb Apartment",
        location: "CBD, Harare",
        price: 65,
        rooms: 1,
        type: "Short Stay",
        borehole: false,
        gated: true,
        solar: false,
    },
    {
        id: 303,
        image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
        title: "Avondale Short-Stay Flat",
        location: "Avondale, Harare",
        price: 70,
        rooms: 2,
        type: "Short Stay",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 304,
        image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
        title: "Mount Pleasant Executive Stay",
        location: "Mount Pleasant, Harare",
        price: 90,
        rooms: 3,
        type: "Short Stay",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 305,
        image: "https://images.unsplash.com/photo-1523217582562-09d0def993a6",
        title: "Cosy Garden Airbnb",
        location: "Greendale, Harare",
        price: 55,
        rooms: 1,
        type: "Short Stay",
        borehole: true,
        gated: false,
        solar: false,
    },
    {
        id: 306,
        image: "https://images.unsplash.com/photo-1590490360182-c33d57733427",
        title: "Newlands Holiday Flat",
        location: "Newlands, Harare",
        price: 75,
        rooms: 2,
        type: "Short Stay",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 307,
        image: "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba",
        title: "Westgate Weekend Stay",
        location: "Westgate, Harare",
        price: 60,
        rooms: 2,
        type: "Short Stay",
        borehole: false,
        gated: true,
        solar: false,
    },
    {
        id: 308,
        image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
        title: "Highlands Luxury Airbnb",
        location: "Highlands, Harare",
        price: 110,
        rooms: 3,
        type: "Short Stay",
        borehole: true,
        gated: true,
        solar: true,
    },
    {
        id: 309,
        image: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6",
        title: "Milton Park Short Stay",
        location: "Milton Park, Harare",
        price: 58,
        rooms: 1,
        type: "Short Stay",
        borehole: true,
        gated: false,
        solar: false,
    },
    {
        id: 310,
        image: "https://images.unsplash.com/photo-1600585152915-d208bec867a1",
        title: "Secure CBD Holiday Apartment",
        location: "Harare CBD",
        price: 62,
        rooms: 1,
        type: "Short Stay",
        borehole: false,
        gated: true,
        solar: false,
    },
];

const Home = () => {
  const [showResults, setShowResults] = useState(false);

  const handleSearch = () => {
    setShowResults(true);
  };

  // We'll just show this dummy list on search for now
//   const allProperties = [
//     ...popularThisWeek,
//     ...newListings,
//     ...guesthouses,
//     ...boardingHouses,
//     ...shortStays,
//   ];


  return (
    <div>
      <Navbar />

      <div style={{ marginTop: "1.5rem" }}>
        {/* Pass the search handler to SearchBar */}
        <SearchBar onSearch={handleSearch} />
      </div>

      {/* Existing property grids */}
      <PropertyGrid title="Popular this week" properties={popularThisWeek} />
      <PropertyGrid title="New listings" properties={newListings} />
      <PropertyGrid title="Comfortable Guesthouses" properties={guesthouses} />
      <PropertyGrid title="Affordable Boarding Houses" properties={boardingHouses} />
      <PropertyGrid title="Short-Stay & Holiday Homes" properties={shortStays} />

      {/* NEW: Show the search results grid only when user clicks search */}


      <Footer />
    </div>
  );
};

export default Home;